apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30009  # Ensure this is within the NodePort range (30000-32767)
  selector:
    app: postgres
